name: Run Tests and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Run Laravel Server
        run: php artisan serve > /dev/null 2>&1 &
      - name: Run Vite Server
        run: npm run build
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test

  web-deploy:
    name: Deploy
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Deploy files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          # SFTP credentials
          host: s10.serv00.com
          port: 22
          user: xahmedtaha
          pass: iM6G(pBC5&5nGQ@1pzkj
          # lftp settings
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          localDir: '.'
          reverse: true
          remoteDir: './domains/xahmedtaha.serv00.net/'
          ignoreFile: '.lftp_ignore'
          options: '--verbose'

      - name: Executing Remote ssh commands
        uses: D3rHase/ssh-command-action@latest
        with:
          host: s10.serv00.com
          port: 22
          user: xahmedtaha
          private_key: "
          -----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAwWCfOsXKUMgMss8iu190bSYysS34jaenLHM+Y1ciqQGtAgUv
KjEj1a3cwpPCUaF77UxdlY9fr3ZOITLZvVN7sgxEHR1uex164Kxnm1m9Yj/0+TX9
Q5za0CRd4DBTjy8JdKbw9uAAdWEY9476VTdYNQbcs1UbVIXGtmV2mQpgyOM9wpEL
aF1XmnwOneslYW85W4Q8N92XC8RH8VNVjj5nqNt1aTxcB4138kNf4PTw/MJYQRWt
djGHhr4mxTHnYdbr3mcdIrTA48THcNXoczb0P+6MCStm7d5U1vBoLMMN6hrX8dfA
+pEf9BABHHH5BiuNWq2bbjncTSpSIZz45iOWnQIDAQABAoIBAAoJw/o/DjOHTvFx
QzJK0DZiRztfUYm47DqoeNKbUVdImPyD3GDqUBvlfJI1LV8jbNVyo2ECIktvbrrW
cusbDE6/yEFip7uIWjqTeIVd8TDKdSMCpHUADXPEj4L1v0CthmYhzFxkYGG3ep5P
M7t8tf16r7Y3csW+dAQ/3BoxqbiDzA5+vBwyb7hRfwa2/IjcLQ4saZoTRz6OUxPM
Q04I/Fg+icDKRqNiTissizXL4r1EHHueycmvlbMgphNNtuLW3sjzlBgvkMzkSp/w
JEbtG3xm5aOfL5TBmdC6j5mnTICO0wnPiRi+9NAIDCcEths/+IOqpXiiD5YRK9p2
gt0CZMECgYEA+YY1qB5ixwRCQvvItq5mrQjJqgxtkNTyjkjPcufB8Yg09KrtHJld
c2CagN2NojcdiOMc/OS5hAfefxk2L1juaf2/kyhdeC4ZPZcedj3K/sgUBzoGqjrT
Q/6G2+m1gkhOhTRIslnhy/QX+zJaHGJIoYoUc5LZmUaSwBfAouaaXLkCgYEAxmVi
Q+o4RqJ5qBl61Qz6jtr4mAChI2xt+LVbd+xyWXCmWkQaA46f329Kx6kFcUzhB1+I
Ao4N9ST/xXluYqjoYpZHvhGLIdingukCh3/QnLXUpW21RtzLD3dPyaZQqBZV6Qq4
0+lfS6XnwVtav+XMqjlownlvmKaEKXf/wQogfwUCgYAi4SDU/FJgcXb1uA5pgt11
aJoP/CbArROu0fy1mjHhGmIUpWP5sHKAs0tFojKvLzcgsGaX7z0DeLogWBzb53mE
NWU3I9hU+VSr6FjovGCI1tz92Z2e5BQuGAEv8m5d5M+dDR7wV2IZyWgkw/gWqaJv
eka7lRZ3t4bB9VAHNWb0eQKBgEYfd4gBtTpiGxXrS5saJ0Vu6Abx0gKvRH9vupC8
pf4u7t1gzMENHDzhHVFM0HunbLIqdexRQWWwWib2MKn2gYy3CUyI7uBbr3l52kcC
Sj3ZlvuRt00ApVUmGrFvc3q1yk/AVmuwRNp8HVoebAj/tENGX1y9h1AxKu1tWJxm
c+3xAoGAdk2nsJ9WCIyeDIN06bgO+OpHbMG4JWuh9zpwkeUpes7ewH03nW5Q88sd
yZoVuuivCnP+wfWdTkgqGiqKcn5LGKyNwK3LrIIFHkEGMJnyUy3hAF9+og2+NS2u
sUcHLZv89ieSAjsAZNTij8BfCTaZVVygdKO0d4mUnFQCZNVZnGA=
-----END RSA PRIVATE KEY-----
          "
          command: |
            cd domains/xahmedtaha.serv00.net/
            composer update
            npm update
            npm run build
            php artisan migrate
            cp -a public/. public_html/
