name: Run Tests and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Run Laravel Server
        run: php artisan serve > /dev/null 2>&1 &
      - name: Run Vite Server
        run: npm run build
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test

  web-deploy:
    name: Deploy
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Deploy files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          # SFTP credentials
          host: s10.serv00.com
          port: 22
          user: xahmedtaha
          pass: iM6G(pBC5&5nGQ@1pzkj
          # lftp settings
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          localDir: '.'
          reverse: true
          remoteDir: './domains/xahmedtaha.serv00.net/'
          ignoreFile: '.lftp_ignore'
          options: '--verbose'

      - name: Executing Remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "s10.serv00.com"
          username: xahmedtaha
          password: iM6G(pBC5&5nGQ@1pzkj
          debug: true
          use_insecure_cipher: true
          port: 22
          script: |
            cd domains/xahmedtaha.serv00.net/
            composer update
            npm update
            npm run build
            php artisan migrate
            cp -a public/. public_html/
