on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
        with:
         fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Deploy files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          # SFTP credentials
          host: s10.serv00.com
          port: 22
          user: xahmedtaha
          pass: iM6G(pBC5&5nGQ@1pzkj
          # lftp settings
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          localDir: '.'
          reverse: true
          remoteDir: '/domains/xahmedtaha.serv00.net/'
          ignoreFile: '.lftp_ignore'
          options: '--verbose' 
     
      - name: Executing Remote ssh commands
        uses: appleboy/ssh-action@v1.0.0
        with:
         host: s10.serv00.com
         username: ${{secrets.SSH_USERNAME}}
         password: ${{secrets.SSH_PRIVATE_KEY}}
         port: 22
         script:  |
              cd domains/xahmedtaha.serv00.net/
              composer update
              npm update
              npm run build
              php artisan migrate
              cp -a public/. public_html/
